simplecost/urls.py
from django.conf.urls import url, include
from auxiliare import urls
from .views import ThirdPartyCreate, PaymentModeCreate, ExpenseListView, ExpenseCreate, ExpenseUpdate, ExpenseDelete, print_it

urlpatterns = [
    url(r'^', include('auxiliare.urls')),
    url(r'^list-expense/$', ExpenseListView.as_view(), name = 'expense-list' ),
    url(r'^create-expense/$', ExpenseCreate.as_view(), name='expense-create'),
    url(r'^update-expense/(?P<pk>\d+)/$', ExpenseUpdate.as_view(), name='expense-update'),
    url(r'^delete-expense/(?P<pk>\d+)/$', ExpenseDelete.as_view(), name='expense-delete'),
    url(r'^create-thirdparty/$', ThirdPartyCreate.as_view(), name='thirdparty-create'),
    url(r'^create-paymentmode/$', PaymentModeCreate.as_view(), name='paymentmode-create'),
    url(r'^print-expense$', print_it, name = 'print-expense-list' ),
]

simplecost/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class ThirdParty(models.Model):
    
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('expense-list')

class PaymentMode(models.Model):
    
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('expense-list')

class Expense(models.Model):
    
    date_expense = models.DateField()
    third_party = models.ForeignKey(ThirdParty, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    notes = models.TextField(max_length=255,blank=True)
    payment_mode = models.ForeignKey(PaymentMode, on_delete=models.CASCADE)
    property_of = models.ForeignKey(User, on_delete=models.CASCADE, related_name='simplecost_owner')
    shared_with = models.ManyToManyField(User, blank=True, related_name='simplecost_user')

    def __str__(self):
        return str(self.date_expense) + '_' + str(self.third_party) + '_' + str(self.amount)
    
    def get_absolute_url(self):
        return reverse('expense-list')
 

simplecost/templates/simplecost/expense_confirm_delete.html
{% load i18n %}
<div class='row' >
	<form action="{% url 'expense-delete' expense.id %}" method="post">
		{% csrf_token %}
		<p class="text-center">{% trans "Do you want to delete this expense" %} ?</p>
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "I'm sure" %}">
		</p>
</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

simplecost/templates/simplecost/expense_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_expense">
		<p class="text-center">{% trans "Expense is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_expense">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Expense isn't created" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" method="post" id="addExpenseSend" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" onclick="reloadPage()" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_expense').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true,
				language: navigator.language
			});
		});
	</script>

	<script type="text/javascript">
		$( '#addExpenseSend' )
			.submit( function( e ) {
				$.ajax( {
					success:  function(resp) {
						$("#response_expense").show();
						setTimeout(function() {
							$("#response_expense").hide();
							$('#addExpenseSend')[0].reset();
						}, 3000 );
					},
					error : function(xhr) {
						$("#error_create_expense").show();
						setTimeout(function() {
							$("#error_create_expense").hide();
						}, 4000 );
					},
					url: '{% url 'expense-create' %}',
					type: 'POST',
					data: new FormData( this ),
					processData: false,
					contentType: false
				} );
				e.preventDefault();
				
			} );
	</script>
	
	<script type="text/javascript">
		function reloadPage() {
			location.reload();
		}
	</script>
	

simplecost/templates/simplecost/expense_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_expense">
		<p class="text-center">{% trans "Expense is updated" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_update_expense">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Expense isn't updated" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" method="post" id="updateExpenseSend" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" onclick="reloadPage()" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_expense').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true,
				language: navigator.language
			});
		});
	</script>

	<script type="text/javascript">
		$( '#updateExpenseSend' )
			.submit( function( e ) {
				$.ajax( {
					success:  function(resp) {
						$("#response_expense").show();
						setTimeout(function() {
							$("#response_expense").hide();
							$('#updateExpenseSend')[0].reset();
						}, 3000 );
					},
					error : function(xhr) {
						$("#error_update_expense").show();
						setTimeout(function() {
							$("#error_update_expense").hide();
						}, 4000 );
					},
					url: '{% url 'expense-update' expense.id %}',
					type: 'POST',
					data: new FormData( this ),
					processData: false,
					contentType: false
				} );
				e.preventDefault();
				
			} );
	</script>
	
	<script type="text/javascript">
		function reloadPage() {
			location.reload();
		}
	</script>
	

simplecost/templates/simplecost/expense_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{% trans "Expense List" %}{% endblock %}

{% block content %}

	<div class='row align-center margin-bottom margin-top'>
		<div class='small-2 medium-4 columns'>
			<p class="text-center show-for-medium"><button class='button' onClick="addExpense()">{% trans "Add an expense" %} <i class="fi-plus"></i></button></p>
			<p class="text-center hide-for-medium"><button class='button' onClick="addExpense()"><i class="fi-plus"></i></button></p>
		</div>
		<div class='small-6 medium-4 columns'>
			<ul class="dropdown menu" data-dropdown-menu>
				<li><a href="#" onClick="filterExpenseCustom('Previous month')"><i class="fi-previous"></i></a></li>
				<li>
					<a href="#" id="sessionFilterExpense">
						{% if request.session.filterexpense == 'Previous month' or request.session.filterexpense == 'Next month' %}
							{{ request.session.filterexpensemonth }}/{{ request.session.filterexpenseyear }}
						{% else %}
							{% trans request.session.filterexpense %}
						{% endif %}
					</a>
					<ul class="menu">
						<li><a href="#" onClick="filterExpense('All','{% trans "All" %}')">{% trans "All" %}</a></li>
						<li><a href="#" onClick="filterExpense('This month','{% trans "This month" %}')">{% trans "This month" %}</a></li>
						<li><a href="#" onClick="filterExpense('This quarter','{% trans "This quarter" %}')">{% trans "This quarter" %}</a></li>
					</ul>
				</li>
				<li><a href="#" onClick="filterExpenseCustom('Next month')"><i class="fi-next"></i></a></li>
			</ul>
		</div>
		<div class='small-2 medium-4 columns'>
			<p class="text-center show-for-medium"><a class='button exportPdf' href="{% url 'print-expense-list' %}" target="_blank"><i class="fi-page-pdf"></i> {% trans "Export to pdf" %}</a></p>
			<p class="text-center hide-for-medium"><a class='button exportPdf' href="{% url 'print-expense-list' %}" target="_blank"><i class="fi-page-pdf"></i></a></p>
		</div>
	</div>
<span id="expense_list_table">
{% if expenses %}
<div class='row margin-bottom margin-top'>
    <table>
        <thead>
			<tr>
                <th></th>
				<th class='text-center'>{% trans "Date" %}</th>
                <th class='text-center'>{% trans "Third Party" %}</th>
                <th class='text-center'>{% trans "Amount" %}</th>
				<th class='text-center'>{% trans "Payment Mode" %}</th>
				<th class='text-center'>{% trans "Notes" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
				<tr>
                    <td>
						<div class="div-align tiny stacked-for-small button-group">
							<button class="warning button" onClick="updateExpense('{% url 'expense-update' expense.id %}')"><i class="fi-pencil"></i></button>
							<button class="alert button" onClick="deleteExpense('{% url 'expense-delete' expense.id %}')"><i class="fi-x"></i></a>
						</div>
					</td>
					<td class='text-center'>{{ expense.date_expense }}</td>
					<td class='text-center'>{{ expense.third_party }}</td>
					<td class='text-center'>{{ expense.amount }}</td>
					<td class='text-center'>{{ expense.payment_mode }}</td>
					<td class='text-center'>{{ expense.notes }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <h1 class=" text-center subheader">{% trans "You don't have any expenses ! Go out ! ;)" %}</h1>
{% endif %}
</span>

	<div class="reveal" id="addExpenseForm" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="updateExpenseForm" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="openThirdPartyForm" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="openPaymentModeForm" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="deleteExpense" data-reveal>
	</div>

{% endblock %}

{% block javascript %}

	<script type="text/javascript">
		function addThirdParty() {
			$.ajax('{% url 'thirdparty-create' %}')
			.done(function(resp){
				$("#openThirdPartyForm").html(resp).foundation('open');
			});
		}
	</script>
	
	<script type="text/javascript">
		function addPaymentMode() {
			$.ajax('{% url 'paymentmode-create' %}')
			.done(function(resp){
				$("#openPaymentModeForm").html(resp).foundation('open');
			});
		}
	</script>

	<script type="text/javascript">
		function addExpense() {
			$.ajax('{% url 'expense-create' %}')
			.done(function(resp){
				$("#addExpenseForm").html(resp).foundation('open');
			});
		}
	</script>
	<script type="text/javascript">
		function updateExpense($idExpense) {
			$.ajax($idExpense)
			.done(function(resp){
				$("#updateExpenseForm").html(resp).foundation('open');
			});
		}
	</script>
	<script type="text/javascript">
		function deleteExpense($idExpense) {
			$.ajax($idExpense)
			.done(function(resp){
				$("#deleteExpense").html(resp).foundation('open');
			});
		}
	</script>
	<script type="text/javascript">
		$(function(){
			$('#filterExpense').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true,
				language: navigator.language
			});
		});
	</script>

	<script type="text/javascript">
		{% if request.session.filterexpense == 'Previous month' or request.session.filterexpense == 'Next month' %}
			var filterExpenseMonth = {{ request.session.filterexpensemonth }};
			var filterExpenseYear = {{ request.session.filterexpenseyear }};
		{% else %}
			var filterExpenseMonth = parseInt('{% now "m" %}');
			var filterExpenseYear = parseInt('{% now "Y" %}');
		{% endif %}

		function filterExpenseCustom(filter){
			$.ajax({
				url:'{% url 'expense-list' %}',
				data: {filter: filter},
				dataType: "html",
				type: 'GET',
				success: function(data){
					$("#expense_list_table").empty().hide();
					$("#expense_list_table").append(data);
					$('#expense_list_table').fadeIn(1000);
					$("#sessionFilterExpense").empty();
					if (filter == 'Previous month'){
						if (filterExpenseMonth == 1) {
							filterExpenseMonth = 12;
							filterExpenseYear = --filterExpenseYear;
						} else {
							filterExpenseMonth = --filterExpenseMonth;
						};
					} else {
						if (filterExpenseMonth == 12) {
							filterExpenseMonth = 1;
							filterExpenseYear = ++filterExpenseYear;
						} else {
							filterExpenseMonth = ++filterExpenseMonth;
						};
					};
					$("#sessionFilterExpense").text(filterExpenseMonth + "/" + filterExpenseYear);
					$("a.exportPdf").prop("href", "{% url 'print-expense-list' %}?filter=" + filter);
					}
				});
		}
	</script>
	<script type="text/javascript">
		function filterExpense(filter,filterExpenseValue){
			$.ajax({
				url:'{% url 'expense-list' %}',
				data: {filter: filter},
				dataType: "html",
				type: 'GET',
				success: function(data){
					$("#expense_list_table").empty().hide();
					$("#expense_list_table").append(data);
					$('#expense_list_table').fadeIn(1000);
					$("#sessionFilterExpense").empty();
					$("#sessionFilterExpense").text(filterExpenseValue);
					filterExpenseMonth = parseInt('{% now "m" %}');
					filterExpenseYear = parseInt('{% now "Y" %}');
					$("a.exportPdf").prop("href", "{% url 'print-expense-list' %}?filter=" + filter);
					}
				});
		}
	</script>
{% endblock %}

simplecost/templates/simplecost/expense_list_table.html
{% load i18n %}
{% load static from staticfiles %}
{% if expenses %}
<div class='row margin-bottom margin-top'>
    <table>
        <thead>
			<tr>
                <th></th>
				<th class='text-center'>{% trans "Date" %}</th>
                <th class='text-center'>{% trans "Third Party" %}</th>
                <th class='text-center'>{% trans "Amount" %}</th>
				<th class='text-center'>{% trans "Payment Mode" %}</th>
				<th class='text-center'>{% trans "Notes" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
				<tr>
                    <td>
						<div class="div-align tiny stacked-for-small button-group">
							<button class="warning button" onClick="updateExpense('{% url 'expense-update' expense.id %}')"><i class="fi-pencil"></i></button>
							<button class="alert button" onClick="deleteExpense('{% url 'expense-delete' expense.id %}')"><i class="fi-x"></i></a>
						</div>
					</td>
					<td class='text-center'>{{ expense.date_expense }}</td>
					<td class='text-center'>{{ expense.third_party }}</td>
					<td class='text-center'>{{ expense.amount }}</td>
					<td class='text-center'>{{ expense.payment_mode }}</td>
					<td class='text-center'>{{ expense.notes }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <h1 class=" text-center subheader">{% trans "You don't have any expenses ! Go out ! ;)" %}</h1>
{% endif %}

simplecost/templates/simplecost/paymentmode_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_paymentmode">
		<p class="text-center">{% trans "Payment Mode" %} <span id="return_paymentmode"></span> {% trans "is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_paymentmode">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Payment Mode isn't created" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" id="addPaymentModeSend" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

<script type="text/javascript">
	$( '#addPaymentModeSend' )
		.submit( function( e ) {
			$.ajax( {
				success:  function(resp){
					document.getElementById("return_paymentmode").innerHTML = resp.name;
					$("#response_paymentmode").show();
					setTimeout(function() {
						$("#response_paymentmode").hide();
						$("#id_payment_mode").append('<option value="'+ resp.pk +'" selected="selected">'+ resp.name + '</option>');
						$("#openPaymentModeForm").html(resp).foundation('close');
					}, 3000 );
				},
				error : function(xhr) {
					$("#error_create_paymentmode").show();
					setTimeout(function() {
						$("#error_create_paymentmode").hide();
					}, 4000 );
				},
				url: '{% url 'paymentmode-create' %}',
				type: 'POST',
				data: new FormData( this ),
				processData: false,
				contentType: false
			} );
			e.preventDefault();
			
		} );
</script>

simplecost/templates/simplecost/thirdparty_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_thirdparty">
		<p class="text-center">{% trans "Third Party" %} <span id="return_thirdparty"></span> {% trans "is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_thirdparty">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Third Party isn't created" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" id="addThirdPartySend" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

<script type="text/javascript">
	$( '#addThirdPartySend' )
		.submit( function( e ) {
			$.ajax( {
				success:  function(resp){
					document.getElementById("return_thirdparty").innerHTML = resp.name;
					$("#response_thirdparty").show();
					setTimeout(function() {
						$("#response_thirdparty").hide();
						$("#id_third_party").append('<option value="'+ resp.pk +'" selected="selected">'+ resp.name + '</option>');
						$("#openThirdPartyForm").html(resp).foundation('close');
					}, 3000 );
				},
				error : function(xhr) {
					$("#error_create_thirdparty").show();
					setTimeout(function() {
						$("#error_create_thirdparty").hide();
					}, 4000 );
				},
				url: '{% url 'thirdparty-create' %}',
				type: 'POST',
				data: new FormData( this ),
				processData: false,
				contentType: false
			} );
			e.preventDefault();
			
		} );
</script>